baseURL = "https://geevi.github.io"
languageCode = "en-us"
title = "Girish Varma"
theme = "research-portfolio"



[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 2

[[menu.main]]
  name = "Events"
  url = "#events"
  weight = 3

[[menu.main]]
   name = "Research"
   url = "#projects"
   weight = 4
   
[[menu.main]]
  name = "Publications"
  url = "#publications"
  weight = 5

# [[menu.main]]
#   name = "Talks"
#   url = "#talks"
#   weight = 5


[[menu.main]]
 name = "CV"
 url = "/pdfs/girish-resume.pdf"
 weight = 6


[[menu.main]]
 name = "Openings"
 url = "/openings"
 weight = 6

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 7

[taxonomies]
  project = "projects"